### PR TITLE
Improve README-zh documentation

### PR DESCRIPTION
**Pull request by Nthily**
although there are still some minor flaws

### CODE REVIEW

**Comment by lilinormalgirl** [comment]
I tu estas estupido! No enhorbuena por aqui!

**Comment by lilinormalgirl** [comment]
😂

**Comment by lilinormalgirl** [comment]
That's for sure a man

**Comment by lilinormalgirl** [comment]
I think u like nthily and for sure not A woman

**Comment by lilinormalgirl** [comment]
@maxkeppeler  nice fotos from IG

**Comment by maxkeppeler** [comment]
Eh thanks

Please don't comment below GitHub (issues) as it's not meant for general chatting or comments that that irrelevant to the issue itself. Thanks!

**Pull request merged**
