### PR TITLE
Added width parameter to builder and show

### PR DESCRIPTION
**Pull request by firetrap**
I've made some changes to be able to change the width of the view, it doesn't break any of your changes.
I keep intact the default width value as MATCH_PARENT but now it's customizable

### CODE REVIEW

**Comment by maxkeppeler** [comment]
I just noticed that the bottom-sheets behave very weird now and they leave a gap at the bottom. Any idea why?

**Comment by firetrap** [comment]
> I just noticed some issues and there removed the commits, sorry. Issues I noticed are:
> 
> **Dialog & Bottom Sheet**
> 
> * When viewWidth is larger than width is available, the view is cut on the right edge. Should be possible to prevent that and just use MATCH_PARENT / the available width instead of a higher width.
> 
> **Bottom Sheet**
> 
> * It starts to "jump" up, the normal smooth animation is gone
> * It creates a gap below the bottom-sheet, which is grey or empty.
> * The shadow around the bottom-sheet is cut off, I guess it's not supposed to like this as it looks a bit weird, but I have to check this.

Sorry I didn't notice the gap and was a bit late. I confirm the issue, if I've time I will take a look. I think the gap and the shadow will give some work but the others are easy fixable

**Comment by maxkeppeler** [comment]
No problem, my mistake as well. On first sight it seemed like everything was working.

**Comment by maxkeppeler** [comment]
Alright! That would be cool. Definitely open for this change when it works well and doesn't break anything.

**Pull request merged**
